// lib/indonesia-regions.ts

export interface Province {
  id: string
  name: string
}

export interface City {
  id: string
  provinceId: string
  name: string
  type: 'kota' | 'kabupaten'
}

export const PROVINCES: Province[] = [
  { id: '11', name: 'Aceh' },
  { id: '12', name: 'Sumatera Utara' },
  { id: '13', name: 'Sumatera Barat' },
  { id: '14', name: 'Riau' },
  { id: '15', name: 'Jambi' },
  { id: '16', name: 'Sumatera Selatan' },
  { id: '17', name: 'Bengkulu' },
  { id: '18', name: 'Lampung' },
  { id: '19', name: 'Kepulauan Bangka Belitung' },
  { id: '21', name: 'Kepulauan Riau' },
  { id: '31', name: 'DKI Jakarta' },
  { id: '32', name: 'Jawa Barat' },
  { id: '33', name: 'Jawa Tengah' },
  { id: '34', name: 'DI Yogyakarta' },
  { id: '35', name: 'Jawa Timur' },
  { id: '36', name: 'Banten' },
  { id: '51', name: 'Bali' },
  { id: '52', name: 'Nusa Tenggara Barat' },
  { id: '53', name: 'Nusa Tenggara Timur' },
  { id: '61', name: 'Kalimantan Barat' },
  { id: '62', name: 'Kalimantan Tengah' },
  { id: '63', name: 'Kalimantan Selatan' },
  { id: '64', name: 'Kalimantan Timur' },
  { id: '65', name: 'Kalimantan Utara' },
  { id: '71', name: 'Sulawesi Utara' },
  { id: '72', name: 'Sulawesi Tengah' },
  { id: '73', name: 'Sulawesi Selatan' },
  { id: '74', name: 'Sulawesi Tenggara' },
  { id: '75', name: 'Gorontalo' },
  { id: '76', name: 'Sulawesi Barat' },
  { id: '81', name: 'Maluku' },
  { id: '82', name: 'Maluku Utara' },
  { id: '91', name: 'Papua Barat' },
  { id: '92', name: 'Papua' },
  { id: '93', name: 'Papua Selatan' },
  { id: '94', name: 'Papua Tengah' },
  { id: '95', name: 'Papua Pegunungan' },
  { id: '96', name: 'Papua Barat Daya' },
]

export const CITIES: City[] = [
  // Aceh
  { id: '1101', provinceId: '11', name: 'Kabupaten Simeulue', type: 'kabupaten' },
  { id: '1102', provinceId: '11', name: 'Kabupaten Aceh Singkil', type: 'kabupaten' },
  { id: '1103', provinceId: '11', name: 'Kabupaten Aceh Selatan', type: 'kabupaten' },
  { id: '1104', provinceId: '11', name: 'Kabupaten Aceh Tenggara', type: 'kabupaten' },
  { id: '1105', provinceId: '11', name: 'Kabupaten Aceh Timur', type: 'kabupaten' },
  { id: '1106', provinceId: '11', name: 'Kabupaten Aceh Tengah', type: 'kabupaten' },
  { id: '1107', provinceId: '11', name: 'Kabupaten Aceh Barat', type: 'kabupaten' },
  { id: '1108', provinceId: '11', name: 'Kabupaten Aceh Besar', type: 'kabupaten' },
  { id: '1109', provinceId: '11', name: 'Kabupaten Pidie', type: 'kabupaten' },
  { id: '1110', provinceId: '11', name: 'Kabupaten Bireuen', type: 'kabupaten' },
  { id: '1111', provinceId: '11', name: 'Kabupaten Aceh Utara', type: 'kabupaten' },
  { id: '1112', provinceId: '11', name: 'Kabupaten Aceh Barat Daya', type: 'kabupaten' },
  { id: '1113', provinceId: '11', name: 'Kabupaten Gayo Lues', type: 'kabupaten' },
  { id: '1114', provinceId: '11', name: 'Kabupaten Aceh Tamiang', type: 'kabupaten' },
  { id: '1115', provinceId: '11', name: 'Kabupaten Nagan Raya', type: 'kabupaten' },
  { id: '1116', provinceId: '11', name: 'Kabupaten Aceh Jaya', type: 'kabupaten' },
  { id: '1117', provinceId: '11', name: 'Kabupaten Bener Meriah', type: 'kabupaten' },
  { id: '1118', provinceId: '11', name: 'Kabupaten Pidie Jaya', type: 'kabupaten' },
  { id: '1171', provinceId: '11', name: 'Kota Banda Aceh', type: 'kota' },
  { id: '1172', provinceId: '11', name: 'Kota Sabang', type: 'kota' },
  { id: '1173', provinceId: '11', name: 'Kota Langsa', type: 'kota' },
  { id: '1174', provinceId: '11', name: 'Kota Lhokseumawe', type: 'kota' },
  { id: '1175', provinceId: '11', name: 'Kota Subulussalam', type: 'kota' },

  // Sumatera Utara
  { id: '1201', provinceId: '12', name: 'Kabupaten Nias', type: 'kabupaten' },
  { id: '1202', provinceId: '12', name: 'Kabupaten Mandailing Natal', type: 'kabupaten' },
  { id: '1203', provinceId: '12', name: 'Kabupaten Tapanuli Selatan', type: 'kabupaten' },
  { id: '1204', provinceId: '12', name: 'Kabupaten Tapanuli Tengah', type: 'kabupaten' },
  { id: '1205', provinceId: '12', name: 'Kabupaten Tapanuli Utara', type: 'kabupaten' },
  { id: '1206', provinceId: '12', name: 'Kabupaten Toba', type: 'kabupaten' },
  { id: '1207', provinceId: '12', name: 'Kabupaten Labuhanbatu', type: 'kabupaten' },
  { id: '1208', provinceId: '12', name: 'Kabupaten Asahan', type: 'kabupaten' },
  { id: '1209', provinceId: '12', name: 'Kabupaten Simalungun', type: 'kabupaten' },
  { id: '1210', provinceId: '12', name: 'Kabupaten Dairi', type: 'kabupaten' },
  { id: '1211', provinceId: '12', name: 'Kabupaten Karo', type: 'kabupaten' },
  { id: '1212', provinceId: '12', name: 'Kabupaten Deli Serdang', type: 'kabupaten' },
  { id: '1213', provinceId: '12', name: 'Kabupaten Langkat', type: 'kabupaten' },
  { id: '1214', provinceId: '12', name: 'Kabupaten Nias Selatan', type: 'kabupaten' },
  { id: '1215', provinceId: '12', name: 'Kabupaten Humbang Hasundutan', type: 'kabupaten' },
  { id: '1216', provinceId: '12', name: 'Kabupaten Pakpak Bharat', type: 'kabupaten' },
  { id: '1217', provinceId: '12', name: 'Kabupaten Samosir', type: 'kabupaten' },
  { id: '1218', provinceId: '12', name: 'Kabupaten Serdang Bedagai', type: 'kabupaten' },
  { id: '1219', provinceId: '12', name: 'Kabupaten Batu Bara', type: 'kabupaten' },
  { id: '1220', provinceId: '12', name: 'Kabupaten Padang Lawas Utara', type: 'kabupaten' },
  { id: '1221', provinceId: '12', name: 'Kabupaten Padang Lawas', type: 'kabupaten' },
  { id: '1222', provinceId: '12', name: 'Kabupaten Labuhanbatu Selatan', type: 'kabupaten' },
  { id: '1223', provinceId: '12', name: 'Kabupaten Labuhanbatu Utara', type: 'kabupaten' },
  { id: '1224', provinceId: '12', name: 'Kabupaten Nias Utara', type: 'kabupaten' },
  { id: '1225', provinceId: '12', name: 'Kabupaten Nias Barat', type: 'kabupaten' },
  { id: '1271', provinceId: '12', name: 'Kota Medan', type: 'kota' },
  { id: '1272', provinceId: '12', name: 'Kota Pematangsiantar', type: 'kota' },
  { id: '1273', provinceId: '12', name: 'Kota Sibolga', type: 'kota' },
  { id: '1274', provinceId: '12', name: 'Kota Tanjungbalai', type: 'kota' },
  { id: '1275', provinceId: '12', name: 'Kota Binjai', type: 'kota' },
  { id: '1276', provinceId: '12', name: 'Kota Tebing Tinggi', type: 'kota' },
  { id: '1277', provinceId: '12', name: 'Kota Padangsidimpuan', type: 'kota' },
  { id: '1278', provinceId: '12', name: 'Kota Gunungsitoli', type: 'kota' },

  // Sumatera Barat
  { id: '1301', provinceId: '13', name: 'Kabupaten Kepulauan Mentawai', type: 'kabupaten' },
  { id: '1302', provinceId: '13', name: 'Kabupaten Pesisir Selatan', type: 'kabupaten' },
  { id: '1303', provinceId: '13', name: 'Kabupaten Solok', type: 'kabupaten' },
  { id: '1304', provinceId: '13', name: 'Kabupaten Sijunjung', type: 'kabupaten' },
  { id: '1305', provinceId: '13', name: 'Kabupaten Tanah Datar', type: 'kabupaten' },
  { id: '1306', provinceId: '13', name: 'Kabupaten Padang Pariaman', type: 'kabupaten' },
  { id: '1307', provinceId: '13', name: 'Kabupaten Agam', type: 'kabupaten' },
  { id: '1308', provinceId: '13', name: 'Kabupaten Lima Puluh Kota', type: 'kabupaten' },
  { id: '1309', provinceId: '13', name: 'Kabupaten Pasaman', type: 'kabupaten' },
  { id: '1310', provinceId: '13', name: 'Kabupaten Solok Selatan', type: 'kabupaten' },
  { id: '1311', provinceId: '13', name: 'Kabupaten Dharmasraya', type: 'kabupaten' },
  { id: '1312', provinceId: '13', name: 'Kabupaten Pasaman Barat', type: 'kabupaten' },
  { id: '1371', provinceId: '13', name: 'Kota Padang', type: 'kota' },
  { id: '1372', provinceId: '13', name: 'Kota Solok', type: 'kota' },
  { id: '1373', provinceId: '13', name: 'Kota Sawahlunto', type: 'kota' },
  { id: '1374', provinceId: '13', name: 'Kota Padangpanjang', type: 'kota' },
  { id: '1375', provinceId: '13', name: 'Kota Bukittinggi', type: 'kota' },
  { id: '1376', provinceId: '13', name: 'Kota Payakumbuh', type: 'kota' },
  { id: '1377', provinceId: '13', name: 'Kota Pariaman', type: 'kota' },

  // Riau
  { id: '1401', provinceId: '14', name: 'Kabupaten Kuantan Singingi', type: 'kabupaten' },
  { id: '1402', provinceId: '14', name: 'Kabupaten Indragiri Hulu', type: 'kabupaten' },
  { id: '1403', provinceId: '14', name: 'Kabupaten Indragiri Hilir', type: 'kabupaten' },
  { id: '1404', provinceId: '14', name: 'Kabupaten Pelalawan', type: 'kabupaten' },
  { id: '1405', provinceId: '14', name: 'Kabupaten Siak', type: 'kabupaten' },
  { id: '1406', provinceId: '14', name: 'Kabupaten Kampar', type: 'kabupaten' },
  { id: '1407', provinceId: '14', name: 'Kabupaten Rokan Hulu', type: 'kabupaten' },
  { id: '1408', provinceId: '14', name: 'Kabupaten Bengkalis', type: 'kabupaten' },
  { id: '1409', provinceId: '14', name: 'Kabupaten Rokan Hilir', type: 'kabupaten' },
  { id: '1410', provinceId: '14', name: 'Kabupaten Kepulauan Meranti', type: 'kabupaten' },
  { id: '1471', provinceId: '14', name: 'Kota Pekanbaru', type: 'kota' },
  { id: '1473', provinceId: '14', name: 'Kota Dumai', type: 'kota' },

  // Jambi
  { id: '1501', provinceId: '15', name: 'Kabupaten Kerinci', type: 'kabupaten' },
  { id: '1502', provinceId: '15', name: 'Kabupaten Merangin', type: 'kabupaten' },
  { id: '1503', provinceId: '15', name: 'Kabupaten Sarolangun', type: 'kabupaten' },
  { id: '1504', provinceId: '15', name: 'Kabupaten Batanghari', type: 'kabupaten' },
  { id: '1505', provinceId: '15', name: 'Kabupaten Muaro Jambi', type: 'kabupaten' },
  { id: '1506', provinceId: '15', name: 'Kabupaten Tanjung Jabung Timur', type: 'kabupaten' },
  { id: '1507', provinceId: '15', name: 'Kabupaten Tanjung Jabung Barat', type: 'kabupaten' },
  { id: '1508', provinceId: '15', name: 'Kabupaten Tebo', type: 'kabupaten' },
  { id: '1509', provinceId: '15', name: 'Kabupaten Bungo', type: 'kabupaten' },
  { id: '1571', provinceId: '15', name: 'Kota Jambi', type: 'kota' },
  { id: '1572', provinceId: '15', name: 'Kota Sungai Penuh', type: 'kota' },

  // Sumatera Selatan
  { id: '1601', provinceId: '16', name: 'Kabupaten Ogan Komering Ulu', type: 'kabupaten' },
  { id: '1602', provinceId: '16', name: 'Kabupaten Ogan Komering Ilir', type: 'kabupaten' },
  { id: '1603', provinceId: '16', name: 'Kabupaten Muara Enim', type: 'kabupaten' },
  { id: '1604', provinceId: '16', name: 'Kabupaten Lahat', type: 'kabupaten' },
  { id: '1605', provinceId: '16', name: 'Kabupaten Musi Rawas', type: 'kabupaten' },
  { id: '1606', provinceId: '16', name: 'Kabupaten Musi Banyuasin', type: 'kabupaten' },
  { id: '1607', provinceId: '16', name: 'Kabupaten Banyu Asin', type: 'kabupaten' },
  { id: '1608', provinceId: '16', name: 'Kabupaten Ogan Komering Ulu Selatan', type: 'kabupaten' },
  { id: '1609', provinceId: '16', name: 'Kabupaten Ogan Komering Ulu Timur', type: 'kabupaten' },
  { id: '1610', provinceId: '16', name: 'Kabupaten Ogan Ilir', type: 'kabupaten' },
  { id: '1611', provinceId: '16', name: 'Kabupaten Empat Lawang', type: 'kabupaten' },
  { id: '1612', provinceId: '16', name: 'Kabupaten Penukal Abab Lematang Ilir', type: 'kabupaten' },
  { id: '1613', provinceId: '16', name: 'Kabupaten Musi Rawas Utara', type: 'kabupaten' },
  { id: '1671', provinceId: '16', name: 'Kota Palembang', type: 'kota' },
  { id: '1672', provinceId: '16', name: 'Kota Prabumulih', type: 'kota' },
  { id: '1673', provinceId: '16', name: 'Kota Pagar Alam', type: 'kota' },
  { id: '1674', provinceId: '16', name: 'Kota Lubuklinggau', type: 'kota' },

  // Bengkulu
  { id: '1701', provinceId: '17', name: 'Kabupaten Bengkulu Selatan', type: 'kabupaten' },
  { id: '1702', provinceId: '17', name: 'Kabupaten Rejang Lebong', type: 'kabupaten' },
  { id: '1703', provinceId: '17', name: 'Kabupaten Bengkulu Utara', type: 'kabupaten' },
  { id: '1704', provinceId: '17', name: 'Kabupaten Kaur', type: 'kabupaten' },
  { id: '1705', provinceId: '17', name: 'Kabupaten Seluma', type: 'kabupaten' },
  { id: '1706', provinceId: '17', name: 'Kabupaten Mukomuko', type: 'kabupaten' },
  { id: '1707', provinceId: '17', name: 'Kabupaten Lebong', type: 'kabupaten' },
  { id: '1708', provinceId: '17', name: 'Kabupaten Kepahiang', type: 'kabupaten' },
  { id: '1709', provinceId: '17', name: 'Kabupaten Bengkulu Tengah', type: 'kabupaten' },
  { id: '1771', provinceId: '17', name: 'Kota Bengkulu', type: 'kota' },

  // Lampung
  { id: '1801', provinceId: '18', name: 'Kabupaten Lampung Barat', type: 'kabupaten' },
  { id: '1802', provinceId: '18', name: 'Kabupaten Tanggamus', type: 'kabupaten' },
  { id: '1803', provinceId: '18', name: 'Kabupaten Lampung Selatan', type: 'kabupaten' },
  { id: '1804', provinceId: '18', name: 'Kabupaten Lampung Timur', type: 'kabupaten' },
  { id: '1805', provinceId: '18', name: 'Kabupaten Lampung Tengah', type: 'kabupaten' },
  { id: '1806', provinceId: '18', name: 'Kabupaten Lampung Utara', type: 'kabupaten' },
  { id: '1807', provinceId: '18', name: 'Kabupaten Way Kanan', type: 'kabupaten' },
  { id: '1808', provinceId: '18', name: 'Kabupaten Tulangbawang', type: 'kabupaten' },
  { id: '1809', provinceId: '18', name: 'Kabupaten Pesawaran', type: 'kabupaten' },
  { id: '1810', provinceId: '18', name: 'Kabupaten Pringsewu', type: 'kabupaten' },
  { id: '1811', provinceId: '18', name: 'Kabupaten Mesuji', type: 'kabupaten' },
  { id: '1812', provinceId: '18', name: 'Kabupaten Tulang Bawang Barat', type: 'kabupaten' },
  { id: '1813', provinceId: '18', name: 'Kabupaten Pesisir Barat', type: 'kabupaten' },
  { id: '1871', provinceId: '18', name: 'Kota Bandar Lampung', type: 'kota' },
  { id: '1872', provinceId: '18', name: 'Kota Metro', type: 'kota' },

  // Kepulauan Bangka Belitung
  { id: '1901', provinceId: '19', name: 'Kabupaten Bangka', type: 'kabupaten' },
  { id: '1902', provinceId: '19', name: 'Kabupaten Belitung', type: 'kabupaten' },
  { id: '1903', provinceId: '19', name: 'Kabupaten Bangka Barat', type: 'kabupaten' },
  { id: '1904', provinceId: '19', name: 'Kabupaten Bangka Tengah', type: 'kabupaten' },
  { id: '1905', provinceId: '19', name: 'Kabupaten Bangka Selatan', type: 'kabupaten' },
  { id: '1906', provinceId: '19', name: 'Kabupaten Belitung Timur', type: 'kabupaten' },
  { id: '1971', provinceId: '19', name: 'Kota Pangkalpinang', type: 'kota' },

  // Kepulauan Riau
  { id: '2101', provinceId: '21', name: 'Kabupaten Karimun', type: 'kabupaten' },
  { id: '2102', provinceId: '21', name: 'Kabupaten Bintan', type: 'kabupaten' },
  { id: '2103', provinceId: '21', name: 'Kabupaten Natuna', type: 'kabupaten' },
  { id: '2104', provinceId: '21', name: 'Kabupaten Lingga', type: 'kabupaten' },
  { id: '2105', provinceId: '21', name: 'Kabupaten Kepulauan Anambas', type: 'kabupaten' },
  { id: '2171', provinceId: '21', name: 'Kota Batam', type: 'kota' },
  { id: '2172', provinceId: '21', name: 'Kota Tanjungpinang', type: 'kota' },

  // DKI Jakarta
  { id: '3101', provinceId: '31', name: 'Kabupaten Kepulauan Seribu', type: 'kabupaten' },
  { id: '3171', provinceId: '31', name: 'Kota Jakarta Selatan', type: 'kota' },
  { id: '3172', provinceId: '31', name: 'Kota Jakarta Timur', type: 'kota' },
  { id: '3173', provinceId: '31', name: 'Kota Jakarta Pusat', type: 'kota' },
  { id: '3174', provinceId: '31', name: 'Kota Jakarta Barat', type: 'kota' },
  { id: '3175', provinceId: '31', name: 'Kota Jakarta Utara', type: 'kota' },

  // Jawa Barat
  { id: '3201', provinceId: '32', name: 'Kabupaten Bogor', type: 'kabupaten' },
  { id: '3202', provinceId: '32', name: 'Kabupaten Sukabumi', type: 'kabupaten' },
  { id: '3203', provinceId: '32', name: 'Kabupaten Cianjur', type: 'kabupaten' },
  { id: '3204', provinceId: '32', name: 'Kabupaten Bandung', type: 'kabupaten' },
  { id: '3205', provinceId: '32', name: 'Kabupaten Garut', type: 'kabupaten' },
  { id: '3206', provinceId: '32', name: 'Kabupaten Tasikmalaya', type: 'kabupaten' },
  { id: '3207', provinceId: '32', name: 'Kabupaten Ciamis', type: 'kabupaten' },
  { id: '3208', provinceId: '32', name: 'Kabupaten Kuningan', type: 'kabupaten' },
  { id: '3209', provinceId: '32', name: 'Kabupaten Cirebon', type: 'kabupaten' },
  { id: '3210', provinceId: '32', name: 'Kabupaten Majalengka', type: 'kabupaten' },
  { id: '3211', provinceId: '32', name: 'Kabupaten Sumedang', type: 'kabupaten' },
  { id: '3212', provinceId: '32', name: 'Kabupaten Indramayu', type: 'kabupaten' },
  { id: '3213', provinceId: '32', name: 'Kabupaten Subang', type: 'kabupaten' },
  { id: '3214', provinceId: '32', name: 'Kabupaten Purwakarta', type: 'kabupaten' },
  { id: '3215', provinceId: '32', name: 'Kabupaten Karawang', type: 'kabupaten' },
  { id: '3216', provinceId: '32', name: 'Kabupaten Bekasi', type: 'kabupaten' },
  { id: '3217', provinceId: '32', name: 'Kabupaten Bandung Barat', type: 'kabupaten' },
  { id: '3218', provinceId: '32', name: 'Kabupaten Pangandaran', type: 'kabupaten' },
  { id: '3271', provinceId: '32', name: 'Kota Bogor', type: 'kota' },
  { id: '3272', provinceId: '32', name: 'Kota Sukabumi', type: 'kota' },
  { id: '3273', provinceId: '32', name: 'Kota Bandung', type: 'kota' },
  { id: '3274', provinceId: '32', name: 'Kota Cirebon', type: 'kota' },
  { id: '3275', provinceId: '32', name: 'Kota Bekasi', type: 'kota' },
  { id: '3276', provinceId: '32', name: 'Kota Depok', type: 'kota' },
  { id: '3277', provinceId: '32', name: 'Kota Cimahi', type: 'kota' },
  { id: '3278', provinceId: '32', name: 'Kota Tasikmalaya', type: 'kota' },
  { id: '3279', provinceId: '32', name: 'Kota Banjar', type: 'kota' },

  // Jawa Tengah
  { id: '3301', provinceId: '33', name: 'Kabupaten Cilacap', type: 'kabupaten' },
  { id: '3302', provinceId: '33', name: 'Kabupaten Banyumas', type: 'kabupaten' },
  { id: '3303', provinceId: '33', name: 'Kabupaten Purbalingga', type: 'kabupaten' },
  { id: '3304', provinceId: '33', name: 'Kabupaten Banjarnegara', type: 'kabupaten' },
  { id: '3305', provinceId: '33', name: 'Kabupaten Kebumen', type: 'kabupaten' },
  { id: '3306', provinceId: '33', name: 'Kabupaten Purworejo', type: 'kabupaten' },
  { id: '3307', provinceId: '33', name: 'Kabupaten Wonosobo', type: 'kabupaten' },
  { id: '3308', provinceId: '33', name: 'Kabupaten Magelang', type: 'kabupaten' },
  { id: '3309', provinceId: '33', name: 'Kabupaten Boyolali', type: 'kabupaten' },
  { id: '3310', provinceId: '33', name: 'Kabupaten Klaten', type: 'kabupaten' },
  { id: '3311', provinceId: '33', name: 'Kabupaten Sukoharjo', type: 'kabupaten' },
  { id: '3312', provinceId: '33', name: 'Kabupaten Wonogiri', type: 'kabupaten' },
  { id: '3313', provinceId: '33', name: 'Kabupaten Karanganyar', type: 'kabupaten' },
  { id: '3314', provinceId: '33', name: 'Kabupaten Sragen', type: 'kabupaten' },
  { id: '3315', provinceId: '33', name: 'Kabupaten Grobogan', type: 'kabupaten' },
  { id: '3316', provinceId: '33', name: 'Kabupaten Blora', type: 'kabupaten' },
  { id: '3317', provinceId: '33', name: 'Kabupaten Rembang', type: 'kabupaten' },
  { id: '3318', provinceId: '33', name: 'Kabupaten Pati', type: 'kabupaten' },
  { id: '3319', provinceId: '33', name: 'Kabupaten Kudus', type: 'kabupaten' },
  { id: '3320', provinceId: '33', name: 'Kabupaten Jepara', type: 'kabupaten' },
  { id: '3321', provinceId: '33', name: 'Kabupaten Demak', type: 'kabupaten' },
  { id: '3322', provinceId: '33', name: 'Kabupaten Semarang', type: 'kabupaten' },
  { id: '3323', provinceId: '33', name: 'Kabupaten Temanggung', type: 'kabupaten' },
  { id: '3324', provinceId: '33', name: 'Kabupaten Kendal', type: 'kabupaten' },
  { id: '3325', provinceId: '33', name: 'Kabupaten Batang', type: 'kabupaten' },
  { id: '3326', provinceId: '33', name: 'Kabupaten Pekalongan', type: 'kabupaten' },
  { id: '3327', provinceId: '33', name: 'Kabupaten Pemalang', type: 'kabupaten' },
  { id: '3328', provinceId: '33', name: 'Kabupaten Tegal', type: 'kabupaten' },
  { id: '3329', provinceId: '33', name: 'Kabupaten Brebes', type: 'kabupaten' },
  { id: '3371', provinceId: '33', name: 'Kota Magelang', type: 'kota' },
  { id: '3372', provinceId: '33', name: 'Kota Surakarta', type: 'kota' },
  { id: '3373', provinceId: '33', name: 'Kota Salatiga', type: 'kota' },
  { id: '3374', provinceId: '33', name: 'Kota Semarang', type: 'kota' },
  { id: '3375', provinceId: '33', name: 'Kota Pekalongan', type: 'kota' },
  { id: '3376', provinceId: '33', name: 'Kota Tegal', type: 'kota' },

  // DI Yogyakarta
  { id: '3401', provinceId: '34', name: 'Kabupaten Kulon Progo', type: 'kabupaten' },
  { id: '3402', provinceId: '34', name: 'Kabupaten Bantul', type: 'kabupaten' },
  { id: '3403', provinceId: '34', name: 'Kabupaten Gunungkidul', type: 'kabupaten' },
  { id: '3404', provinceId: '34', name: 'Kabupaten Sleman', type: 'kabupaten' },
  { id: '3471', provinceId: '34', name: 'Kota Yogyakarta', type: 'kota' },

  // Jawa Timur
  { id: '3501', provinceId: '35', name: 'Kabupaten Pacitan', type: 'kabupaten' },
  { id: '3502', provinceId: '35', name: 'Kabupaten Ponorogo', type: 'kabupaten' },
  { id: '3503', provinceId: '35', name: 'Kabupaten Trenggalek', type: 'kabupaten' },
  { id: '3504', provinceId: '35', name: 'Kabupaten Tulungagung', type: 'kabupaten' },
  { id: '3505', provinceId: '35', name: 'Kabupaten Blitar', type: 'kabupaten' },
  { id: '3506', provinceId: '35', name: 'Kabupaten Kediri', type: 'kabupaten' },
  { id: '3507', provinceId: '35', name: 'Kabupaten Malang', type: 'kabupaten' },
  { id: '3508', provinceId: '35', name: 'Kabupaten Lumajang', type: 'kabupaten' },
  { id: '3509', provinceId: '35', name: 'Kabupaten Jember', type: 'kabupaten' },
  { id: '3510', provinceId: '35', name: 'Kabupaten Banyuwangi', type: 'kabupaten' },
  { id: '3511', provinceId: '35', name: 'Kabupaten Bondowoso', type: 'kabupaten' },
  { id: '3512', provinceId: '35', name: 'Kabupaten Situbondo', type: 'kabupaten' },
  { id: '3513', provinceId: '35', name: 'Kabupaten Probolinggo', type: 'kabupaten' },
  { id: '3514', provinceId: '35', name: 'Kabupaten Pasuruan', type: 'kabupaten' },
  { id: '3515', provinceId: '35', name: 'Kabupaten Sidoarjo', type: 'kabupaten' },
  { id: '3516', provinceId: '35', name: 'Kabupaten Mojokerto', type: 'kabupaten' },
  { id: '3517', provinceId: '35', name: 'Kabupaten Jombang', type: 'kabupaten' },
  { id: '3518', provinceId: '35', name: 'Kabupaten Nganjuk', type: 'kabupaten' },
  { id: '3519', provinceId: '35', name: 'Kabupaten Madiun', type: 'kabupaten' },
  { id: '3520', provinceId: '35', name: 'Kabupaten Magetan', type: 'kabupaten' },
  { id: '3521', provinceId: '35', name: 'Kabupaten Ngawi', type: 'kabupaten' },
  { id: '3522', provinceId: '35', name: 'Kabupaten Bojonegoro', type: 'kabupaten' },
  { id: '3523', provinceId: '35', name: 'Kabupaten Tuban', type: 'kabupaten' },
  { id: '3524', provinceId: '35', name: 'Kabupaten Lamongan', type: 'kabupaten' },
  { id: '3525', provinceId: '35', name: 'Kabupaten Gresik', type: 'kabupaten' },
  { id: '3526', provinceId: '35', name: 'Kabupaten Bangkalan', type: 'kabupaten' },
  { id: '3527', provinceId: '35', name: 'Kabupaten Sampang', type: 'kabupaten' },
  { id: '3528', provinceId: '35', name: 'Kabupaten Pamekasan', type: 'kabupaten' },
  { id: '3529', provinceId: '35', name: 'Kabupaten Sumenep', type: 'kabupaten' },
  { id: '3571', provinceId: '35', name: 'Kota Kediri', type: 'kota' },
  { id: '3572', provinceId: '35', name: 'Kota Blitar', type: 'kota' },
  { id: '3573', provinceId: '35', name: 'Kota Malang', type: 'kota' },
  { id: '3574', provinceId: '35', name: 'Kota Probolinggo', type: 'kota' },
  { id: '3575', provinceId: '35', name: 'Kota Pasuruan', type: 'kota' },
  { id: '3576', provinceId: '35', name: 'Kota Mojokerto', type: 'kota' },
  { id: '3577', provinceId: '35', name: 'Kota Madiun', type: 'kota' },
  { id: '3578', provinceId: '35', name: 'Kota Surabaya', type: 'kota' },
  { id: '3579', provinceId: '35', name: 'Kota Batu', type: 'kota' },

  // Banten
  { id: '3601', provinceId: '36', name: 'Kabupaten Pandeglang', type: 'kabupaten' },
  { id: '3602', provinceId: '36', name: 'Kabupaten Lebak', type: 'kabupaten' },
  { id: '3603', provinceId: '36', name: 'Kabupaten Tangerang', type: 'kabupaten' },
  { id: '3604', provinceId: '36', name: 'Kabupaten Serang', type: 'kabupaten' },
  { id: '3671', provinceId: '36', name: 'Kota Tangerang', type: 'kota' },
  { id: '3672', provinceId: '36', name: 'Kota Cilegon', type: 'kota' },
  { id: '3673', provinceId: '36', name: 'Kota Serang', type: 'kota' },
  { id: '3674', provinceId: '36', name: 'Kota Tangerang Selatan', type: 'kota' },

  // Bali
  { id: '5101', provinceId: '51', name: 'Kabupaten Jembrana', type: 'kabupaten' },
  { id: '5102', provinceId: '51', name: 'Kabupaten Tabanan', type: 'kabupaten' },
  { id: '5103', provinceId: '51', name: 'Kabupaten Badung', type: 'kabupaten' },
  { id: '5104', provinceId: '51', name: 'Kabupaten Gianyar', type: 'kabupaten' },
  { id: '5105', provinceId: '51', name: 'Kabupaten Klungkung', type: 'kabupaten' },
  { id: '5106', provinceId: '51', name: 'Kabupaten Bangli', type: 'kabupaten' },
  { id: '5107', provinceId: '51', name: 'Kabupaten Karangasem', type: 'kabupaten' },
  { id: '5108', provinceId: '51', name: 'Kabupaten Buleleng', type: 'kabupaten' },
  { id: '5171', provinceId: '51', name: 'Kota Denpasar', type: 'kota' },

  // NTB
  { id: '5201', provinceId: '52', name: 'Kabupaten Lombok Barat', type: 'kabupaten' },
  { id: '5202', provinceId: '52', name: 'Kabupaten Lombok Tengah', type: 'kabupaten' },
  { id: '5203', provinceId: '52', name: 'Kabupaten Lombok Timur', type: 'kabupaten' },
  { id: '5204', provinceId: '52', name: 'Kabupaten Sumbawa', type: 'kabupaten' },
  { id: '5205', provinceId: '52', name: 'Kabupaten Dompu', type: 'kabupaten' },
  { id: '5206', provinceId: '52', name: 'Kabupaten Bima', type: 'kabupaten' },
  { id: '5207', provinceId: '52', name: 'Kabupaten Sumbawa Barat', type: 'kabupaten' },
  { id: '5208', provinceId: '52', name: 'Kabupaten Lombok Utara', type: 'kabupaten' },
  { id: '5271', provinceId: '52', name: 'Kota Mataram', type: 'kota' },
  { id: '5272', provinceId: '52', name: 'Kota Bima', type: 'kota' },

  // NTT
  { id: '5301', provinceId: '53', name: 'Kabupaten Sumba Barat', type: 'kabupaten' },
  { id: '5302', provinceId: '53', name: 'Kabupaten Sumba Timur', type: 'kabupaten' },
  { id: '5303', provinceId: '53', name: 'Kabupaten Kupang', type: 'kabupaten' },
  { id: '5304', provinceId: '53', name: 'Kabupaten Timor Tengah Selatan', type: 'kabupaten' },
  { id: '5305', provinceId: '53', name: 'Kabupaten Timor Tengah Utara', type: 'kabupaten' },
  { id: '5306', provinceId: '53', name: 'Kabupaten Belu', type: 'kabupaten' },
  { id: '5307', provinceId: '53', name: 'Kabupaten Alor', type: 'kabupaten' },
  { id: '5308', provinceId: '53', name: 'Kabupaten Lembata', type: 'kabupaten' },
  { id: '5309', provinceId: '53', name: 'Kabupaten Flores Timur', type: 'kabupaten' },
  { id: '5310', provinceId: '53', name: 'Kabupaten Sikka', type: 'kabupaten' },
  { id: '5311', provinceId: '53', name: 'Kabupaten Ende', type: 'kabupaten' },
  { id: '5312', provinceId: '53', name: 'Kabupaten Ngada', type: 'kabupaten' },
  { id: '5313', provinceId: '53', name: 'Kabupaten Manggarai', type: 'kabupaten' },
  { id: '5314', provinceId: '53', name: 'Kabupaten Rote Ndao', type: 'kabupaten' },
  { id: '5315', provinceId: '53', name: 'Kabupaten Manggarai Barat', type: 'kabupaten' },
  { id: '5316', provinceId: '53', name: 'Kabupaten Sumba Tengah', type: 'kabupaten' },
  { id: '5317', provinceId: '53', name: 'Kabupaten Sumba Barat Daya', type: 'kabupaten' },
  { id: '5318', provinceId: '53', name: 'Kabupaten Nagekeo', type: 'kabupaten' },
  { id: '5319', provinceId: '53', name: 'Kabupaten Manggarai Timur', type: 'kabupaten' },
  { id: '5320', provinceId: '53', name: 'Kabupaten Sabu Raijua', type: 'kabupaten' },
  { id: '5321', provinceId: '53', name: 'Kabupaten Malaka', type: 'kabupaten' },
  { id: '5371', provinceId: '53', name: 'Kota Kupang', type: 'kota' },

  // Kalimantan Barat
  { id: '6101', provinceId: '61', name: 'Kabupaten Sambas', type: 'kabupaten' },
  { id: '6102', provinceId: '61', name: 'Kabupaten Mempawah', type: 'kabupaten' },
  { id: '6103', provinceId: '61', name: 'Kabupaten Sanggau', type: 'kabupaten' },
  { id: '6104', provinceId: '61', name: 'Kabupaten Ketapang', type: 'kabupaten' },
  { id: '6105', provinceId: '61', name: 'Kabupaten Sintang', type: 'kabupaten' },
  { id: '6106', provinceId: '61', name: 'Kabupaten Kapuas Hulu', type: 'kabupaten' },
  { id: '6107', provinceId: '61', name: 'Kabupaten Bengkayang', type: 'kabupaten' },
  { id: '6108', provinceId: '61', name: 'Kabupaten Landak', type: 'kabupaten' },
  { id: '6109', provinceId: '61', name: 'Kabupaten Sekadau', type: 'kabupaten' },
  { id: '6110', provinceId: '61', name: 'Kabupaten Melawi', type: 'kabupaten' },
  { id: '6111', provinceId: '61', name: 'Kabupaten Kayong Utara', type: 'kabupaten' },
  { id: '6112', provinceId: '61', name: 'Kabupaten Kubu Raya', type: 'kabupaten' },
  { id: '6171', provinceId: '61', name: 'Kota Pontianak', type: 'kota' },
  { id: '6172', provinceId: '61', name: 'Kota Singkawang', type: 'kota' },

  // Kalimantan Tengah
  { id: '6201', provinceId: '62', name: 'Kabupaten Kotawaringin Barat', type: 'kabupaten' },
  { id: '6202', provinceId: '62', name: 'Kabupaten Kotawaringin Timur', type: 'kabupaten' },
  { id: '6203', provinceId: '62', name: 'Kabupaten Kapuas', type: 'kabupaten' },
  { id: '6204', provinceId: '62', name: 'Kabupaten Barito Selatan', type: 'kabupaten' },
  { id: '6205', provinceId: '62', name: 'Kabupaten Barito Utara', type: 'kabupaten' },
  { id: '6206', provinceId: '62', name: 'Kabupaten Sukamara', type: 'kabupaten' },
  { id: '6207', provinceId: '62', name: 'Kabupaten Lamandau', type: 'kabupaten' },
  { id: '6208', provinceId: '62', name: 'Kabupaten Seruyan', type: 'kabupaten' },
  { id: '6209', provinceId: '62', name: 'Kabupaten Katingan', type: 'kabupaten' },
  { id: '6210', provinceId: '62', name: 'Kabupaten Pulang Pisau', type: 'kabupaten' },
  { id: '6211', provinceId: '62', name: 'Kabupaten Gunung Mas', type: 'kabupaten' },
  { id: '6212', provinceId: '62', name: 'Kabupaten Barito Timur', type: 'kabupaten' },
  { id: '6213', provinceId: '62', name: 'Kabupaten Murung Raya', type: 'kabupaten' },
  { id: '6271', provinceId: '62', name: 'Kota Palangka Raya', type: 'kota' },

  // Kalimantan Selatan
  { id: '6301', provinceId: '63', name: 'Kabupaten Tanah Laut', type: 'kabupaten' },
  { id: '6302', provinceId: '63', name: 'Kabupaten Kotabaru', type: 'kabupaten' },
  { id: '6303', provinceId: '63', name: 'Kabupaten Banjar', type: 'kabupaten' },
  { id: '6304', provinceId: '63', name: 'Kabupaten Barito Kuala', type: 'kabupaten' },
  { id: '6305', provinceId: '63', name: 'Kabupaten Tapin', type: 'kabupaten' },
  { id: '6306', provinceId: '63', name: 'Kabupaten Hulu Sungai Selatan', type: 'kabupaten' },
  { id: '6307', provinceId: '63', name: 'Kabupaten Hulu Sungai Tengah', type: 'kabupaten' },
  { id: '6308', provinceId: '63', name: 'Kabupaten Hulu Sungai Utara', type: 'kabupaten' },
  { id: '6309', provinceId: '63', name: 'Kabupaten Tabalong', type: 'kabupaten' },
  { id: '6310', provinceId: '63', name: 'Kabupaten Tanah Bumbu', type: 'kabupaten' },
  { id: '6311', provinceId: '63', name: 'Kabupaten Balangan', type: 'kabupaten' },
  { id: '6371', provinceId: '63', name: 'Kota Banjarmasin', type: 'kota' },
  { id: '6372', provinceId: '63', name: 'Kota Banjarbaru', type: 'kota' },

  // Kalimantan Timur
  { id: '6401', provinceId: '64', name: 'Kabupaten Paser', type: 'kabupaten' },
  { id: '6402', provinceId: '64', name: 'Kabupaten Kutai Barat', type: 'kabupaten' },
  { id: '6403', provinceId: '64', name: 'Kabupaten Kutai Kartanegara', type: 'kabupaten' },
  { id: '6404', provinceId: '64', name: 'Kabupaten Kutai Timur', type: 'kabupaten' },
  { id: '6405', provinceId: '64', name: 'Kabupaten Berau', type: 'kabupaten' },
  { id: '6409', provinceId: '64', name: 'Kabupaten Penajam Paser Utara', type: 'kabupaten' },
  { id: '6411', provinceId: '64', name: 'Kabupaten Mahakam Ulu', type: 'kabupaten' },
  { id: '6471', provinceId: '64', name: 'Kota Balikpapan', type: 'kota' },
  { id: '6472', provinceId: '64', name: 'Kota Samarinda', type: 'kota' },
  { id: '6474', provinceId: '64', name: 'Kota Bontang', type: 'kota' },

  // Kalimantan Utara
  { id: '6501', provinceId: '65', name: 'Kabupaten Malinau', type: 'kabupaten' },
  { id: '6502', provinceId: '65', name: 'Kabupaten Bulungan', type: 'kabupaten' },
  { id: '6503', provinceId: '65', name: 'Kabupaten Tana Tidung', type: 'kabupaten' },
  { id: '6504', provinceId: '65', name: 'Kabupaten Nunukan', type: 'kabupaten' },
  { id: '6571', provinceId: '65', name: 'Kota Tarakan', type: 'kota' },

  // Sulawesi Utara
  { id: '7101', provinceId: '71', name: 'Kabupaten Bolaang Mongondow', type: 'kabupaten' },
  { id: '7102', provinceId: '71', name: 'Kabupaten Minahasa', type: 'kabupaten' },
  { id: '7103', provinceId: '71', name: 'Kabupaten Kepulauan Sangihe', type: 'kabupaten' },
  { id: '7104', provinceId: '71', name: 'Kabupaten Kepulauan Talaud', type: 'kabupaten' },
  { id: '7105', provinceId: '71', name: 'Kabupaten Minahasa Selatan', type: 'kabupaten' },
  { id: '7106', provinceId: '71', name: 'Kabupaten Minahasa Utara', type: 'kabupaten' },
  { id: '7107', provinceId: '71', name: 'Kabupaten Bolaang Mongondow Utara', type: 'kabupaten' },
  { id: '7108', provinceId: '71', name: 'Kabupaten Kepulauan Siau Tagulandang Biaro', type: 'kabupaten' },
  { id: '7109', provinceId: '71', name: 'Kabupaten Minahasa Tenggara', type: 'kabupaten' },
  { id: '7110', provinceId: '71', name: 'Kabupaten Bolaang Mongondow Selatan', type: 'kabupaten' },
  { id: '7111', provinceId: '71', name: 'Kabupaten Bolaang Mongondow Timur', type: 'kabupaten' },
  { id: '7171', provinceId: '71', name: 'Kota Manado', type: 'kota' },
  { id: '7172', provinceId: '71', name: 'Kota Bitung', type: 'kota' },
  { id: '7173', provinceId: '71', name: 'Kota Tomohon', type: 'kota' },
  { id: '7174', provinceId: '71', name: 'Kota Kotamobagu', type: 'kota' },

  // Sulawesi Tengah
  { id: '7201', provinceId: '72', name: 'Kabupaten Banggai Kepulauan', type: 'kabupaten' },
  { id: '7202', provinceId: '72', name: 'Kabupaten Banggai', type: 'kabupaten' },
  { id: '7203', provinceId: '72', name: 'Kabupaten Morowali', type: 'kabupaten' },
  { id: '7204', provinceId: '72', name: 'Kabupaten Poso', type: 'kabupaten' },
  { id: '7205', provinceId: '72', name: 'Kabupaten Donggala', type: 'kabupaten' },
  { id: '7206', provinceId: '72', name: 'Kabupaten Toli-Toli', type: 'kabupaten' },
  { id: '7207', provinceId: '72', name: 'Kabupaten Buol', type: 'kabupaten' },
  { id: '7208', provinceId: '72', name: 'Kabupaten Parigi Moutong', type: 'kabupaten' },
  { id: '7209', provinceId: '72', name: 'Kabupaten Tojo Una-Una', type: 'kabupaten' },
  { id: '7210', provinceId: '72', name: 'Kabupaten Sigi', type: 'kabupaten' },
  { id: '7211', provinceId: '72', name: 'Kabupaten Banggai Laut', type: 'kabupaten' },
  { id: '7212', provinceId: '72', name: 'Kabupaten Morowali Utara', type: 'kabupaten' },
  { id: '7271', provinceId: '72', name: 'Kota Palu', type: 'kota' },

  // Sulawesi Selatan
  { id: '7301', provinceId: '73', name: 'Kabupaten Kepulauan Selayar', type: 'kabupaten' },
  { id: '7302', provinceId: '73', name: 'Kabupaten Bulukumba', type: 'kabupaten' },
  { id: '7303', provinceId: '73', name: 'Kabupaten Bantaeng', type: 'kabupaten' },
  { id: '7304', provinceId: '73', name: 'Kabupaten Jeneponto', type: 'kabupaten' },
  { id: '7305', provinceId: '73', name: 'Kabupaten Takalar', type: 'kabupaten' },
  { id: '7306', provinceId: '73', name: 'Kabupaten Gowa', type: 'kabupaten' },
  { id: '7307', provinceId: '73', name: 'Kabupaten Sinjai', type: 'kabupaten' },
  { id: '7308', provinceId: '73', name: 'Kabupaten Maros', type: 'kabupaten' },
  { id: '7309', provinceId: '73', name: 'Kabupaten Pangkajene dan Kepulauan', type: 'kabupaten' },
  { id: '7310', provinceId: '73', name: 'Kabupaten Barru', type: 'kabupaten' },
  { id: '7311', provinceId: '73', name: 'Kabupaten Bone', type: 'kabupaten' },
  { id: '7312', provinceId: '73', name: 'Kabupaten Soppeng', type: 'kabupaten' },
  { id: '7313', provinceId: '73', name: 'Kabupaten Wajo', type: 'kabupaten' },
  { id: '7314', provinceId: '73', name: 'Kabupaten Sidenreng Rappang', type: 'kabupaten' },
  { id: '7315', provinceId: '73', name: 'Kabupaten Pinrang', type: 'kabupaten' },
  { id: '7316', provinceId: '73', name: 'Kabupaten Enrekang', type: 'kabupaten' },
  { id: '7317', provinceId: '73', name: 'Kabupaten Luwu', type: 'kabupaten' },
  { id: '7318', provinceId: '73', name: 'Kabupaten Tana Toraja', type: 'kabupaten' },
  { id: '7322', provinceId: '73', name: 'Kabupaten Luwu Utara', type: 'kabupaten' },
  { id: '7325', provinceId: '73', name: 'Kabupaten Luwu Timur', type: 'kabupaten' },
  { id: '7326', provinceId: '73', name: 'Kabupaten Toraja Utara', type: 'kabupaten' },
  { id: '7371', provinceId: '73', name: 'Kota Makassar', type: 'kota' },
  { id: '7372', provinceId: '73', name: 'Kota Pare-Pare', type: 'kota' },
  { id: '7373', provinceId: '73', name: 'Kota Palopo', type: 'kota' },

  // Sulawesi Tenggara
  { id: '7401', provinceId: '74', name: 'Kabupaten Buton', type: 'kabupaten' },
  { id: '7402', provinceId: '74', name: 'Kabupaten Muna', type: 'kabupaten' },
  { id: '7403', provinceId: '74', name: 'Kabupaten Konawe', type: 'kabupaten' },
  { id: '7404', provinceId: '74', name: 'Kabupaten Kolaka', type: 'kabupaten' },
  { id: '7405', provinceId: '74', name: 'Kabupaten Konawe Selatan', type: 'kabupaten' },
  { id: '7406', provinceId: '74', name: 'Kabupaten Bombana', type: 'kabupaten' },
  { id: '7407', provinceId: '74', name: 'Kabupaten Wakatobi', type: 'kabupaten' },
  { id: '7408', provinceId: '74', name: 'Kabupaten Kolaka Utara', type: 'kabupaten' },
  { id: '7409', provinceId: '74', name: 'Kabupaten Buton Utara', type: 'kabupaten' },
  { id: '7410', provinceId: '74', name: 'Kabupaten Konawe Utara', type: 'kabupaten' },
  { id: '7411', provinceId: '74', name: 'Kabupaten Kolaka Timur', type: 'kabupaten' },
  { id: '7412', provinceId: '74', name: 'Kabupaten Konawe Kepulauan', type: 'kabupaten' },
  { id: '7413', provinceId: '74', name: 'Kabupaten Muna Barat', type: 'kabupaten' },
  { id: '7414', provinceId: '74', name: 'Kabupaten Buton Tengah', type: 'kabupaten' },
  { id: '7415', provinceId: '74', name: 'Kabupaten Buton Selatan', type: 'kabupaten' },
  { id: '7471', provinceId: '74', name: 'Kota Kendari', type: 'kota' },
  { id: '7472', provinceId: '74', name: 'Kota Bau-Bau', type: 'kota' },

  // Gorontalo
  { id: '7501', provinceId: '75', name: 'Kabupaten Boalemo', type: 'kabupaten' },
  { id: '7502', provinceId: '75', name: 'Kabupaten Gorontalo', type: 'kabupaten' },
  { id: '7503', provinceId: '75', name: 'Kabupaten Pohuwato', type: 'kabupaten' },
  { id: '7504', provinceId: '75', name: 'Kabupaten Bone Bolango', type: 'kabupaten' },
  { id: '7505', provinceId: '75', name: 'Kabupaten Gorontalo Utara', type: 'kabupaten' },
  { id: '7571', provinceId: '75', name: 'Kota Gorontalo', type: 'kota' },

  // Sulawesi Barat
  { id: '7601', provinceId: '76', name: 'Kabupaten Mamuju', type: 'kabupaten' },
  { id: '7602', provinceId: '76', name: 'Kabupaten Majene', type: 'kabupaten' },
  { id: '7603', provinceId: '76', name: 'Kabupaten Polewali Mandar', type: 'kabupaten' },
  { id: '7604', provinceId: '76', name: 'Kabupaten Mamasa', type: 'kabupaten' },
  { id: '7605', provinceId: '76', name: 'Kabupaten Pasangkayu', type: 'kabupaten' },
  { id: '7606', provinceId: '76', name: 'Kabupaten Mamuju Tengah', type: 'kabupaten' },

  // Maluku
  { id: '8101', provinceId: '81', name: 'Kabupaten Maluku Tengah', type: 'kabupaten' },
  { id: '8102', provinceId: '81', name: 'Kabupaten Maluku Tenggara', type: 'kabupaten' },
  { id: '8103', provinceId: '81', name: 'Kabupaten Kepulauan Tanimbar', type: 'kabupaten' },
  { id: '8104', provinceId: '81', name: 'Kabupaten Maluku Tenggara Barat', type: 'kabupaten' },
  { id: '8105', provinceId: '81', name: 'Kabupaten Buru', type: 'kabupaten' },
  { id: '8106', provinceId: '81', name: 'Kabupaten Seram Bagian Timur', type: 'kabupaten' },
  { id: '8107', provinceId: '81', name: 'Kabupaten Seram Bagian Barat', type: 'kabupaten' },
  { id: '8108', provinceId: '81', name: 'Kabupaten Kepulauan Aru', type: 'kabupaten' },
  { id: '8109', provinceId: '81', name: 'Kabupaten Maluku Barat Daya', type: 'kabupaten' },
  { id: '8110', provinceId: '81', name: 'Kabupaten Buru Selatan', type: 'kabupaten' },
  { id: '8171', provinceId: '81', name: 'Kota Ambon', type: 'kota' },
  { id: '8172', provinceId: '81', name: 'Kota Tual', type: 'kota' },

  // Maluku Utara
  { id: '8201', provinceId: '82', name: 'Kabupaten Halmahera Barat', type: 'kabupaten' },
  { id: '8202', provinceId: '82', name: 'Kabupaten Halmahera Tengah', type: 'kabupaten' },
  { id: '8203', provinceId: '82', name: 'Kabupaten Kepulauan Sula', type: 'kabupaten' },
  { id: '8204', provinceId: '82', name: 'Kabupaten Halmahera Selatan', type: 'kabupaten' },
  { id: '8205', provinceId: '82', name: 'Kabupaten Halmahera Utara', type: 'kabupaten' },
  { id: '8206', provinceId: '82', name: 'Kabupaten Halmahera Timur', type: 'kabupaten' },
  { id: '8207', provinceId: '82', name: 'Kabupaten Pulau Morotai', type: 'kabupaten' },
  { id: '8208', provinceId: '82', name: 'Kabupaten Pulau Taliabu', type: 'kabupaten' },
  { id: '8271', provinceId: '82', name: 'Kota Ternate', type: 'kota' },
  { id: '8272', provinceId: '82', name: 'Kota Tidore Kepulauan', type: 'kota' },

  // Papua Barat
  { id: '9101', provinceId: '91', name: 'Kabupaten Fak-Fak', type: 'kabupaten' },
  { id: '9102', provinceId: '91', name: 'Kabupaten Kaimana', type: 'kabupaten' },
  { id: '9103', provinceId: '91', name: 'Kabupaten Teluk Wondama', type: 'kabupaten' },
  { id: '9104', provinceId: '91', name: 'Kabupaten Teluk Bintuni', type: 'kabupaten' },
  { id: '9105', provinceId: '91', name: 'Kabupaten Manokwari', type: 'kabupaten' },
  { id: '9106', provinceId: '91', name: 'Kabupaten Sorong Selatan', type: 'kabupaten' },
  { id: '9107', provinceId: '91', name: 'Kabupaten Sorong', type: 'kabupaten' },
  { id: '9108', provinceId: '91', name: 'Kabupaten Raja Ampat', type: 'kabupaten' },
  { id: '9109', provinceId: '91', name: 'Kabupaten Tambrauw', type: 'kabupaten' },
  { id: '9110', provinceId: '91', name: 'Kabupaten Maybrat', type: 'kabupaten' },
  { id: '9111', provinceId: '91', name: 'Kabupaten Manokwari Selatan', type: 'kabupaten' },
  { id: '9112', provinceId: '91', name: 'Kabupaten Pegunungan Arfak', type: 'kabupaten' },
  { id: '9171', provinceId: '91', name: 'Kota Sorong', type: 'kota' },

  // Papua
  { id: '9201', provinceId: '92', name: 'Kabupaten Merauke', type: 'kabupaten' },
  { id: '9202', provinceId: '92', name: 'Kabupaten Jayawijaya', type: 'kabupaten' },
  { id: '9203', provinceId: '92', name: 'Kabupaten Jayapura', type: 'kabupaten' },
  { id: '9204', provinceId: '92', name: 'Kabupaten Nabire', type: 'kabupaten' },
  { id: '9208', provinceId: '92', name: 'Kabupaten Kepulauan Yapen', type: 'kabupaten' },
  { id: '9209', provinceId: '92', name: 'Kabupaten Biak Numfor', type: 'kabupaten' },
  { id: '9210', provinceId: '92', name: 'Kabupaten Sarmi', type: 'kabupaten' },
  { id: '9211', provinceId: '92', name: 'Kabupaten Keerom', type: 'kabupaten' },
  { id: '9218', provinceId: '92', name: 'Kabupaten Waropen', type: 'kabupaten' },
  { id: '9219', provinceId: '92', name: 'Kabupaten Supiori', type: 'kabupaten' },
  { id: '9220', provinceId: '92', name: 'Kabupaten Mamberamo Raya', type: 'kabupaten' },
  { id: '9226', provinceId: '92', name: 'Kabupaten Mamberamo Tengah', type: 'kabupaten' },
  { id: '9227', provinceId: '92', name: 'Kabupaten Yalimo', type: 'kabupaten' },
  { id: '9228', provinceId: '92', name: 'Kabupaten Lanny Jaya', type: 'kabupaten' },
  { id: '9229', provinceId: '92', name: 'Kabupaten Nduga', type: 'kabupaten' },
  { id: '9230', provinceId: '92', name: 'Kabupaten Kepulauan Mambai', type: 'kabupaten' },
  { id: '9271', provinceId: '92', name: 'Kota Jayapura', type: 'kota' },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Ambil semua provinsi, sudah urut nama */
export function getProvinces(): Province[] {
  return [...PROVINCES].sort((a, b) => a.name.localeCompare(b.name, 'id'))
}

/** Ambil kota/kabupaten berdasarkan provinceId, sudah urut: Kota dulu lalu Kabupaten */
export function getCitiesByProvince(provinceId: string): City[] {
  return CITIES
    .filter(c => c.provinceId === provinceId)
    .sort((a, b) => {
      if (a.type !== b.type) return a.type === 'kota' ? -1 : 1
      return a.name.localeCompare(b.name, 'id')
    })
}

/** Cari nama provinsi berdasarkan ID */
export function getProvinceName(provinceId: string): string {
  return PROVINCES.find(p => p.id === provinceId)?.name ?? ''
}

/** Cari nama kota berdasarkan ID */
export function getCityName(cityId: string): string {
  return CITIES.find(c => c.id === cityId)?.name ?? ''
}

/** Cari provinceId dari nama provinsi (untuk backward compat data lama) */
export function getProvinceIdByName(name: string): string {
  const normalized = name.trim().toLowerCase()
  return PROVINCES.find(p => p.name.toLowerCase() === normalized)?.id ?? ''
}

/** Cari cityId dari nama kota (untuk backward compat data lama) */
export function getCityIdByName(name: string): string {
  const normalized = name.trim().toLowerCase()
  return CITIES.find(c => c.name.toLowerCase() === normalized)?.id ?? ''
}